sudo: false
dist: trusty
language: python
python: # The following versions
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib
  - pip install tensorflow
script:
  # run all python files in parallel, http://stackoverflow.com/questions/5015316
  - find codes/python/ -type f -name "*.py" |xargs -n 1 -P 3 python
